/** Legacy static categories — used for DB import and dev fallback. */
export const LEGACY_CATEGORIES = [
  {
    name: "Pizza Toppings",
    items: [
      { slug: "pepperoni", label: "Pepperoni", wiki_title: "Pepperoni" },
      { slug: "mushroom", label: "Mushroom", wiki_title: "Mushroom" },
      { slug: "pineapple", label: "Pineapple", wiki_title: "Pineapple" },
      { slug: "olives", label: "Olives", wiki_title: "Olive" },
      { slug: "onion", label: "Onion", wiki_title: "Onion" },
      { slug: "pepper", label: "Bell Pepper", wiki_title: "Bell pepper" },
      { slug: "sausage", label: "Sausage", wiki_title: "Sausage" },
      { slug: "bacon", label: "Bacon", wiki_title: "Bacon" },
      { slug: "jalapeno", label: "Jalapeño", wiki_title: "Jalapeño" },
      { slug: "garlic", label: "Garlic", wiki_title: "Garlic" },
      { slug: "spinach", label: "Spinach", wiki_title: "Spinach" },
      { slug: "anchovy", label: "Anchovy", wiki_title: "Anchovy" },
      { slug: "tomato", label: "Tomato", wiki_title: "Tomato" },
      { slug: "corn", label: "Corn", wiki_title: "Maize" },
      { slug: "pesto", label: "Pesto", wiki_title: "Pesto" },
    ],
  },
  {
    name: "Breakfast Foods",
    items: [
      { slug: "pancakes", label: "Pancakes", wiki_title: "Pancake" },
      { slug: "waffles", label: "Waffles", wiki_title: "Waffle" },
      { slug: "bacon", label: "Bacon", wiki_title: "Bacon" },
      { slug: "eggs", label: "Eggs", wiki_title: "Egg as food" },
      { slug: "toast", label: "Toast", wiki_title: "Toast (food)" },
      { slug: "bagel", label: "Bagel", wiki_title: "Bagel" },
      { slug: "cereal", label: "Cereal", wiki_title: "Breakfast cereal" },
      { slug: "oatmeal", label: "Oatmeal", wiki_title: "Oatmeal" },
      { slug: "yogurt", label: "Yogurt", wiki_title: "Yogurt" },
      { slug: "fruit", label: "Fresh Fruit", wiki_title: "Fruit" },
      { slug: "sausage", label: "Sausage", wiki_title: "Sausage" },
      { slug: "hash", label: "Hash Browns", wiki_title: "Hash browns" },
      { slug: "avocado", label: "Avocado Toast", wiki_title: "Avocado toast" },
      { slug: "smoothie", label: "Smoothie", wiki_title: "Smoothie" },
      { slug: "donut", label: "Donut", wiki_title: "Doughnut" },
    ],
  },
  {
    name: "Movie Snacks",
    items: [
      { slug: "popcorn", label: "Popcorn", wiki_title: "Popcorn" },
      { slug: "nachos", label: "Nachos", wiki_title: "Nachos" },
      { slug: "candy", label: "Candy", wiki_title: "Candy" },
      { slug: "soda", label: "Soda", wiki_title: "Soft drink" },
      { slug: "pretzel", label: "Pretzel", wiki_title: "Pretzel" },
      { slug: "hotdog", label: "Hot Dog", wiki_title: "Hot dog" },
      { slug: "pizza", label: "Pizza Slice", wiki_title: "Pizza" },
      { slug: "icecream", label: "Ice Cream", wiki_title: "Ice cream" },
      { slug: "chips", label: "Chips", wiki_title: "Potato chip" },
      { slug: "cookie", label: "Cookie", wiki_title: "Cookie" },
      { slug: "water", label: "Water", wiki_title: "Bottled water" },
      { slug: "wine", label: "Wine", wiki_title: "Wine" },
      { slug: "slushie", label: "Slushie", wiki_title: "Slushy" },
      { slug: "churro", label: "Churro", wiki_title: "Churro" },
      { slug: "pickles", label: "Pickles", wiki_title: "Pickled cucumber" },
    ],
  },
] as const;
