#!/usr/bin/env tsx
/**
 * scripts/build-country-borders.ts
 *
 * Works out which countries share a land border from the outlines the map already ships
 * (public/anyguessr/world-countries-110m.geojson), and writes lib/anyguessr/country-borders.ts.
 * Neighbouring countries in Natural Earth share exact border vertices, so two countries are
 * neighbours when they share at least two of them (one shared point is a corner, not a border).
 *
 * Usage: npx tsx scripts/build-country-borders.ts
 */

import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "public/anyguessr/world-countries-110m.geojson";
const OUT = "lib/anyguessr/country-borders.ts";

async function main() {
  const { cca3FromFeature } = await import("../lib/anyguessr/country-at-point");
  const world = JSON.parse(readFileSync(SOURCE, "utf8")) as GeoJSON.FeatureCollection;

  const at = new Map<string, Set<string>>();
  const note = (cca3: string, [lng, lat]: number[]) => {
    const key = `${lng.toFixed(4)},${lat.toFixed(4)}`;
    const set = at.get(key) ?? new Set<string>();
    set.add(cca3);
    at.set(key, set);
  };

  for (const feature of world.features) {
    const cca3 = cca3FromFeature(feature);
    if (!cca3 || !feature.geometry) continue;
    const polygons =
      feature.geometry.type === "Polygon" ? [feature.geometry.coordinates] : feature.geometry.type === "MultiPolygon" ? feature.geometry.coordinates : [];
    for (const polygon of polygons) for (const ring of polygon) for (const vertex of ring) note(cca3, vertex);
  }

  const shared = new Map<string, number>();
  for (const countries of at.values()) {
    const list = [...countries].sort();
    for (let i = 0; i < list.length; i++) {
      for (let j = i + 1; j < list.length; j++) {
        const pair = `${list[i]}:${list[j]}`;
        shared.set(pair, (shared.get(pair) ?? 0) + 1);
      }
    }
  }

  const neighbours: Record<string, string[]> = {};
  for (const [pair, count] of shared) {
    if (count < 2) continue;
    const [a, b] = pair.split(":");
    (neighbours[a] ??= []).push(b);
    (neighbours[b] ??= []).push(a);
  }

  const lines = Object.keys(neighbours)
    .sort()
    .map((cca3) => `  ${cca3}: ${JSON.stringify(neighbours[cca3].sort())},`);

  writeFileSync(
    OUT,
    `// Generated by scripts/build-country-borders.ts from the map's own outlines. Do not edit by hand.\n\n` +
      `/** Countries that share a land border, by ISO 3166-1 alpha-3 code. Island nations have none. */\n` +
      `export const COUNTRY_BORDERS: Readonly<Record<string, readonly string[]>> = {\n${lines.join("\n")}\n};\n\n` +
      `export function sharesBorder(a: string | null | undefined, b: string | null | undefined): boolean {\n` +
      `  return Boolean(a && b && COUNTRY_BORDERS[a]?.includes(b));\n}\n`,
  );
  console.log(`${Object.keys(neighbours).length} countries with at least one land neighbour -> ${OUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
