#!/usr/bin/env tsx
/**
 * Seed script: Populates chain_phrases with a large set of common
 * two-word English phrases for the chain puzzle generator.
 *
 * Usage: npx tsx scripts/seed-phrases.ts
 */

import { config } from "dotenv";

config({ path: ".env.local" });
import { createClient } from "@supabase/supabase-js";

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!url || !key) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const db = createClient(url, key);

/* ------------------------------------------------------------------ */
/*  Phrase database by category                                        */
/* ------------------------------------------------------------------ */

interface PhraseEntry {
  word_a: string;
  word_b: string;
  score: number;
  category: string;
}

const PHRASES: PhraseEntry[] = [
  // FOOD & DRINK
  { word_a: "apple", word_b: "juice", score: 9, category: "food" },
  { word_a: "orange", word_b: "juice", score: 9, category: "food" },
  { word_a: "lemon", word_b: "juice", score: 8, category: "food" },
  { word_a: "grape", word_b: "juice", score: 7, category: "food" },
  { word_a: "tomato", word_b: "juice", score: 7, category: "food" },
  { word_a: "fruit", word_b: "juice", score: 8, category: "food" },
  { word_a: "coffee", word_b: "cup", score: 9, category: "food" },
  { word_a: "tea", word_b: "cup", score: 8, category: "food" },
  { word_a: "paper", word_b: "cup", score: 7, category: "food" },
  { word_a: "cup", word_b: "cake", score: 9, category: "food" },
  { word_a: "pound", word_b: "cake", score: 8, category: "food" },
  { word_a: "cheese", word_b: "cake", score: 7, category: "food" },
  { word_a: "pancake", word_b: "mix", score: 6, category: "food" },
  { word_a: "cake", word_b: "walk", score: 7, category: "food" },
  { word_a: "walk", word_b: "away", score: 7, category: "food" },
  { word_a: "walk", word_b: "out", score: 8, category: "food" },
  { word_a: "walk", word_b: "over", score: 6, category: "food" },
  { word_a: "walk", word_b: "through", score: 8, category: "food" },
  { word_a: "walk", word_b: "way", score: 7, category: "food" },
  { word_a: "milk", word_b: "shake", score: 9, category: "food" },
  { word_a: "hand", word_b: "shake", score: 9, category: "food" },
  { word_a: "shake", word_b: "down", score: 6, category: "food" },
  { word_a: "shake", word_b: "up", score: 7, category: "food" },
  { word_a: "ice", word_b: "cream", score: 10, category: "food" },
  { word_a: "whipped", word_b: "cream", score: 8, category: "food" },
  { word_a: "cream", word_b: "cheese", score: 9, category: "food" },
  { word_a: "macaroni", word_b: "cheese", score: 8, category: "food" },
  { word_a: "cottage", word_b: "cheese", score: 8, category: "food" },
  { word_a: "cheese", word_b: "burger", score: 9, category: "food" },
  { word_a: "ham", word_b: "burger", score: 7, category: "food" },
  { word_a: "veggie", word_b: "burger", score: 7, category: "food" },
  { word_a: "chicken", word_b: "soup", score: 8, category: "food" },
  { word_a: "tomato", word_b: "soup", score: 8, category: "food" },
  { word_a: "mushroom", word_b: "soup", score: 7, category: "food" },
  { word_a: "soup", word_b: "kitchen", score: 6, category: "food" },
  { word_a: "bread", word_b: "basket", score: 7, category: "food" },
  { word_a: "bread", word_b: "crumb", score: 7, category: "food" },
  { word_a: "corn", word_b: "bread", score: 8, category: "food" },
  { word_a: "short", word_b: "bread", score: 8, category: "food" },
  { word_a: "honey", word_b: "bee", score: 8, category: "food" },
  { word_a: "bee", word_b: "hive", score: 7, category: "nature" },
  { word_a: "sugar", word_b: "bowl", score: 7, category: "food" },
  { word_a: "candy", word_b: "bar", score: 9, category: "food" },
  { word_a: "chocolate", word_b: "bar", score: 9, category: "food" },
  { word_a: "granola", word_b: "bar", score: 8, category: "food" },
  { word_a: "salad", word_b: "bar", score: 7, category: "food" },
  { word_a: "salad", word_b: "dressing", score: 8, category: "food" },
  { word_a: "bar", word_b: "stool", score: 7, category: "home" },
  { word_a: "bar", word_b: "table", score: 7, category: "home" },
  { word_a: "bar", word_b: "tender", score: 8, category: "food" },
  { word_a: "peanut", word_b: "butter", score: 9, category: "food" },
  { word_a: "butter", word_b: "fly", score: 9, category: "nature" },
  { word_a: "peanut", word_b: "oil", score: 7, category: "food" },
  { word_a: "olive", word_b: "oil", score: 9, category: "food" },
  { word_a: "cooking", word_b: "oil", score: 8, category: "food" },
  { word_a: "oil", word_b: "change", score: 7, category: "transport" },
  { word_a: "oil", word_b: "spill", score: 6, category: "nature" },
  { word_a: "spill", word_b: "over", score: 6, category: "general" },
  { word_a: "spill", word_b: "out", score: 6, category: "general" },
  { word_a: "bacon", word_b: "strips", score: 7, category: "food" },
  { word_a: "chicken", word_b: "wing", score: 8, category: "food" },
  { word_a: "wing", word_b: "man", score: 6, category: "general" },
  { word_a: "hot", word_b: "dog", score: 10, category: "food" },
  { word_a: "dog", word_b: "food", score: 9, category: "animals" },
  { word_a: "dog", word_b: "house", score: 8, category: "animals" },
  { word_a: "dog", word_b: "park", score: 9, category: "animals" },
  { word_a: "dog", word_b: "days", score: 7, category: "time" },

  // NATURE & WEATHER
  { word_a: "snow", word_b: "ball", score: 9, category: "nature" },
  { word_a: "snow", word_b: "flake", score: 8, category: "nature" },
  { word_a: "snow", word_b: "storm", score: 8, category: "nature" },
  { word_a: "snow", word_b: "man", score: 9, category: "nature" },
  { word_a: "snow", word_b: "fall", score: 8, category: "nature" },
  { word_a: "rain", word_b: "bow", score: 10, category: "nature" },
  { word_a: "rain", word_b: "drop", score: 8, category: "nature" },
  { word_a: "rain", word_b: "storm", score: 9, category: "nature" },
  { word_a: "rain", word_b: "coat", score: 8, category: "nature" },
  { word_a: "rain", word_b: "fall", score: 7, category: "nature" },
  { word_a: "rain", word_b: "water", score: 8, category: "nature" },
  { word_a: "storm", word_b: "cloud", score: 8, category: "nature" },
  { word_a: "storm", word_b: "door", score: 6, category: "nature" },
  { word_a: "storm", word_b: "surge", score: 6, category: "nature" },
  { word_a: "cloud", word_b: "nine", score: 7, category: "nature" },
  { word_a: "cloud", word_b: "burst", score: 7, category: "nature" },
  { word_a: "sun", word_b: "flower", score: 9, category: "nature" },
  { word_a: "sun", word_b: "rise", score: 9, category: "nature" },
  { word_a: "sun", word_b: "set", score: 9, category: "nature" },
  { word_a: "sun", word_b: "light", score: 8, category: "nature" },
  { word_a: "sun", word_b: "beam", score: 7, category: "nature" },
  { word_a: "moon", word_b: "light", score: 9, category: "nature" },
  { word_a: "moon", word_b: "walk", score: 7, category: "nature" },
  { word_a: "moon", word_b: "beam", score: 7, category: "nature" },
  { word_a: "light", word_b: "house", score: 9, category: "nature" },
  { word_a: "light", word_b: "year", score: 8, category: "nature" },
  { word_a: "light", word_b: "bulb", score: 8, category: "home" },
  { word_a: "light", word_b: "ning", score: 9, category: "nature" },
  { word_a: "star", word_b: "fish", score: 9, category: "nature" },
  { word_a: "star", word_b: "light", score: 8, category: "nature" },
  { word_a: "star", word_b: "dust", score: 7, category: "nature" },
  { word_a: "star", word_b: "ship", score: 8, category: "transport" },
  { word_a: "sea", word_b: "shell", score: 9, category: "nature" },
  { word_a: "sea", word_b: "horse", score: 8, category: "nature" },
  { word_a: "sea", word_b: "weed", score: 7, category: "nature" },
  { word_a: "sea", word_b: "food", score: 7, category: "food" },
  { word_a: "ocean", word_b: "wave", score: 8, category: "nature" },
  { word_a: "wave", word_b: "pool", score: 8, category: "nature" },
  { word_a: "tide", word_b: "pool", score: 7, category: "nature" },
  { word_a: "pool", word_b: "table", score: 7, category: "home" },
  { word_a: "water", word_b: "fall", score: 10, category: "nature" },
  { word_a: "water", word_b: "melon", score: 8, category: "food" },
  { word_a: "water", word_b: "bottle", score: 9, category: "home" },
  { word_a: "water", word_b: "color", score: 7, category: "arts" },
  { word_a: "water", word_b: "front", score: 7, category: "nature" },
  { word_a: "river", word_b: "bank", score: 8, category: "nature" },
  { word_a: "river", word_b: "bed", score: 7, category: "nature" },
  { word_a: "river", word_b: "boat", score: 8, category: "transport" },
  { word_a: "sand", word_b: "castle", score: 8, category: "nature" },
  { word_a: "sand", word_b: "paper", score: 7, category: "education" },
  { word_a: "fire", word_b: "fly", score: 9, category: "nature" },
  { word_a: "fire", word_b: "place", score: 9, category: "home" },
  { word_a: "fire", word_b: "man", score: 8, category: "general" },
  { word_a: "fire", word_b: "work", score: 9, category: "general" },
  { word_a: "fire", word_b: "fighter", score: 9, category: "general" },
  { word_a: "brush", word_b: "fire", score: 8, category: "nature" },
  { word_a: "forest", word_b: "fire", score: 7, category: "nature" },
  { word_a: "place", word_b: "mat", score: 8, category: "home" },
  { word_a: "place", word_b: "ment", score: 7, category: "general" },
  { word_a: "night", word_b: "fall", score: 9, category: "time" },
  { word_a: "night", word_b: "time", score: 9, category: "time" },
  { word_a: "night", word_b: "mare", score: 8, category: "general" },
  { word_a: "night", word_b: "gown", score: 7, category: "home" },
  { word_a: "night", word_b: "light", score: 7, category: "home" },

  // BODY & HEALTH
  { word_a: "head", word_b: "ache", score: 8, category: "health" },
  { word_a: "head", word_b: "light", score: 8, category: "health" },
  { word_a: "head", word_b: "line", score: 7, category: "general" },
  { word_a: "head", word_b: "room", score: 7, category: "home" },
  { word_a: "head", word_b: "start", score: 7, category: "general" },
  { word_a: "head", word_b: "way", score: 6, category: "transport" },
  { word_a: "eye", word_b: "lash", score: 9, category: "health" },
  { word_a: "eye", word_b: "brow", score: 9, category: "health" },
  { word_a: "eye", word_b: "lid", score: 8, category: "health" },
  { word_a: "eye", word_b: "sight", score: 8, category: "health" },
  { word_a: "eye", word_b: "ball", score: 7, category: "health" },
  { word_a: "eye", word_b: "shadow", score: 8, category: "health" },
  { word_a: "ear", word_b: "drum", score: 8, category: "health" },
  { word_a: "ear", word_b: "ring", score: 7, category: "health" },
  { word_a: "nose", word_b: "bleed", score: 7, category: "health" },
  { word_a: "nose", word_b: "cone", score: 7, category: "health" },
  { word_a: "lip", word_b: "stick", score: 8, category: "health" },
  { word_a: "lip", word_b: "gloss", score: 8, category: "health" },
  { word_a: "tooth", word_b: "brush", score: 10, category: "health" },
  { word_a: "tooth", word_b: "paste", score: 9, category: "health" },
  { word_a: "tooth", word_b: "pick", score: 7, category: "health" },
  { word_a: "tooth", word_b: "ache", score: 7, category: "health" },
  { word_a: "arm", word_b: "chair", score: 9, category: "home" },
  { word_a: "arm", word_b: "pit", score: 8, category: "health" },
  { word_a: "arm", word_b: "rest", score: 7, category: "home" },
  { word_a: "arm", word_b: "band", score: 6, category: "health" },
  { word_a: "hand", word_b: "bag", score: 8, category: "home" },
  { word_a: "hand", word_b: "book", score: 8, category: "education" },
  { word_a: "hand", word_b: "cuff", score: 7, category: "home" },
  { word_a: "hand", word_b: "ful", score: 7, category: "general" },
  { word_a: "hand", word_b: "le", score: 6, category: "general" },
  { word_a: "finger", word_b: "print", score: 9, category: "health" },
  { word_a: "finger", word_b: "nail", score: 8, category: "health" },
  { word_a: "finger", word_b: "tip", score: 7, category: "health" },
  { word_a: "thumb", word_b: "nail", score: 7, category: "health" },
  { word_a: "thumb", word_b: "print", score: 7, category: "health" },
  { word_a: "foot", word_b: "ball", score: 10, category: "sports" },
  { word_a: "foot", word_b: "print", score: 8, category: "health" },
  { word_a: "foot", word_b: "step", score: 7, category: "health" },
  { word_a: "foot", word_b: "wear", score: 7, category: "health" },
  { word_a: "back", word_b: "bone", score: 9, category: "health" },
  { word_a: "back", word_b: "pack", score: 9, category: "home" },
  { word_a: "back", word_b: "yard", score: 9, category: "home" },
  { word_a: "back", word_b: "ground", score: 8, category: "general" },
  { word_a: "back", word_b: "track", score: 7, category: "general" },
  { word_a: "bone", word_b: "yard", score: 7, category: "animals" },
  { word_a: "brain", word_b: "storm", score: 9, category: "education" },
  { word_a: "brain", word_b: "wave", score: 7, category: "education" },
  { word_a: "heart", word_b: "beat", score: 9, category: "health" },
  { word_a: "heart", word_b: "ache", score: 8, category: "health" },
  { word_a: "heart", word_b: "burn", score: 8, category: "health" },
  { word_a: "heart", word_b: "land", score: 7, category: "general" },

  // HOME & FURNITURE
  { word_a: "bed", word_b: "room", score: 10, category: "home" },
  { word_a: "bed", word_b: "sheet", score: 8, category: "home" },
  { word_a: "bed", word_b: "frame", score: 7, category: "home" },
  { word_a: "bed", word_b: "time", score: 8, category: "home" },
  { word_a: "room", word_b: "mate", score: 9, category: "home" },
  { word_a: "room", word_b: "service", score: 7, category: "home" },
  { word_a: "bath", word_b: "room", score: 10, category: "home" },
  { word_a: "bath", word_b: "tub", score: 9, category: "home" },
  { word_a: "bath", word_b: "robe", score: 8, category: "home" },
  { word_a: "bath", word_b: "towel", score: 8, category: "home" },
  { word_a: "bath", word_b: "mat", score: 8, category: "home" },
  { word_a: "bath", word_b: "salt", score: 7, category: "home" },
  { word_a: "salt", word_b: "shaker", score: 7, category: "food" },
  { word_a: "salt", word_b: "water", score: 7, category: "food" },
  { word_a: "living", word_b: "room", score: 10, category: "home" },
  { word_a: "dining", word_b: "room", score: 9, category: "home" },
  { word_a: "waiting", word_b: "room", score: 8, category: "home" },
  { word_a: "kitchen", word_b: "table", score: 8, category: "home" },
  { word_a: "kitchen", word_b: "sink", score: 8, category: "home" },
  { word_a: "table", word_b: "cloth", score: 8, category: "home" },
  { word_a: "table", word_b: "spoon", score: 7, category: "home" },
  { word_a: "table", word_b: "top", score: 7, category: "home" },
  { word_a: "table", word_b: "ware", score: 7, category: "home" },
  { word_a: "door", word_b: "bell", score: 9, category: "home" },
  { word_a: "door", word_b: "step", score: 9, category: "home" },
  { word_a: "door", word_b: "way", score: 8, category: "home" },
  { word_a: "door", word_b: "frame", score: 7, category: "home" },
  { word_a: "door", word_b: "knob", score: 8, category: "home" },
  { word_a: "door", word_b: "man", score: 7, category: "home" },
  { word_a: "door", word_b: "stop", score: 7, category: "home" },
  { word_a: "window", word_b: "sill", score: 8, category: "home" },
  { word_a: "window", word_b: "pane", score: 8, category: "home" },
  { word_a: "window", word_b: "frame", score: 7, category: "home" },
  { word_a: "wall", word_b: "paper", score: 8, category: "home" },
  { word_a: "wall", word_b: "street", score: 6, category: "transport" },
  { word_a: "floor", word_b: "plan", score: 7, category: "home" },
  { word_a: "floor", word_b: "board", score: 7, category: "home" },
  { word_a: "floor", word_b: "mat", score: 7, category: "home" },
  { word_a: "ceiling", word_b: "fan", score: 8, category: "home" },
  { word_a: "fan", word_b: "club", score: 6, category: "music" },
  { word_a: "chair", word_b: "lift", score: 8, category: "home" },
  { word_a: "chair", word_b: "man", score: 8, category: "home" },
  { word_a: "chair", word_b: "person", score: 6, category: "home" },
  { word_a: "sofa", word_b: "bed", score: 7, category: "home" },

  // TRANSPORT
  { word_a: "car", word_b: "wash", score: 9, category: "transport" },
  { word_a: "car", word_b: "port", score: 8, category: "transport" },
  { word_a: "car", word_b: "park", score: 9, category: "transport" },
  { word_a: "car", word_b: "seat", score: 8, category: "transport" },
  { word_a: "car", word_b: "pool", score: 8, category: "transport" },
  { word_a: "car", word_b: "key", score: 7, category: "transport" },
  { word_a: "park", word_b: "ing", score: 8, category: "transport" },
  { word_a: "park", word_b: "bench", score: 8, category: "nature" },
  { word_a: "park", word_b: "way", score: 7, category: "transport" },
  { word_a: "road", word_b: "trip", score: 9, category: "transport" },
  { word_a: "road", word_b: "side", score: 8, category: "transport" },
  { word_a: "road", word_b: "block", score: 7, category: "transport" },
  { word_a: "road", word_b: "kill", score: 7, category: "transport" },
  { word_a: "high", word_b: "way", score: 9, category: "transport" },
  { word_a: "high", word_b: "wayman", score: 6, category: "transport" },
  { word_a: "free", word_b: "way", score: 9, category: "transport" },
  { word_a: "free", word_b: "dom", score: 7, category: "general" },
  { word_a: "free", word_b: "time", score: 8, category: "general" },
  { word_a: "rail", word_b: "road", score: 8, category: "transport" },
  { word_a: "rail", word_b: "way", score: 7, category: "transport" },
  { word_a: "side", word_b: "walk", score: 9, category: "transport" },
  { word_a: "side", word_b: "line", score: 7, category: "general" },
  { word_a: "side", word_b: "ways", score: 6, category: "general" },
  { word_a: "air", word_b: "port", score: 10, category: "transport" },
  { word_a: "air", word_b: "plane", score: 9, category: "transport" },
  { word_a: "air", word_b: "line", score: 8, category: "transport" },
  { word_a: "air", word_b: "mail", score: 7, category: "transport" },
  { word_a: "air", word_b: "space", score: 8, category: "nature" },
  { word_a: "air", word_b: "bag", score: 7, category: "transport" },
  { word_a: "air", word_b: "drop", score: 7, category: "transport" },
  { word_a: "plane", word_b: "ticket", score: 8, category: "transport" },
  { word_a: "train", word_b: "station", score: 9, category: "transport" },
  { word_a: "train", word_b: "track", score: 8, category: "transport" },
  { word_a: "bus", word_b: "stop", score: 9, category: "transport" },
  { word_a: "bus", word_b: "station", score: 8, category: "transport" },
  { word_a: "bus", word_b: "route", score: 7, category: "transport" },
  { word_a: "stop", word_b: "light", score: 8, category: "transport" },
  { word_a: "stop", word_b: "sign", score: 8, category: "transport" },
  { word_a: "stop", word_b: "over", score: 7, category: "transport" },
  { word_a: "truck", word_b: "stop", score: 7, category: "transport" },
  { word_a: "boat", word_b: "house", score: 8, category: "transport" },
  { word_a: "boat", word_b: "yard", score: 7, category: "transport" },
  { word_a: "ship", word_b: "yard", score: 7, category: "transport" },
  { word_a: "ship", word_b: "wreck", score: 7, category: "transport" },
  { word_a: "bike", word_b: "rack", score: 7, category: "transport" },
  { word_a: "bike", word_b: "path", score: 7, category: "transport" },
  { word_a: "bike", word_b: "lane", score: 7, category: "transport" },

  // SPORTS & GAMES
  { word_a: "ball", word_b: "room", score: 8, category: "sports" },
  { word_a: "ball", word_b: "park", score: 8, category: "sports" },
  { word_a: "ball", word_b: "game", score: 8, category: "sports" },
  { word_a: "ball", word_b: "point", score: 7, category: "sports" },
  { word_a: "basket", word_b: "ball", score: 10, category: "sports" },
  { word_a: "base", word_b: "ball", score: 10, category: "sports" },
  { word_a: "volley", word_b: "ball", score: 9, category: "sports" },
  { word_a: "soft", word_b: "ball", score: 9, category: "sports" },
  { word_a: "snow", word_b: "board", score: 9, category: "sports" },
  { word_a: "skate", word_b: "board", score: 9, category: "sports" },
  { word_a: "key", word_b: "board", score: 9, category: "sports" },
  { word_a: "board", word_b: "game", score: 9, category: "sports" },
  { word_a: "board", word_b: "room", score: 7, category: "home" },
  { word_a: "board", word_b: "walk", score: 7, category: "nature" },
  { word_a: "game", word_b: "plan", score: 8, category: "sports" },
  { word_a: "game", word_b: "show", score: 8, category: "sports" },
  { word_a: "game", word_b: "keeper", score: 7, category: "sports" },
  { word_a: "video", word_b: "game", score: 9, category: "technology" },
  { word_a: "field", word_b: "goal", score: 8, category: "sports" },
  { word_a: "field", word_b: "work", score: 7, category: "general" },
  { word_a: "field", word_b: "trip", score: 8, category: "education" },
  { word_a: "field", word_b: "day", score: 7, category: "sports" },
  { word_a: "goal", word_b: "keeper", score: 8, category: "sports" },
  { word_a: "goal", word_b: "post", score: 7, category: "sports" },
  { word_a: "goal", word_b: "line", score: 7, category: "sports" },
  { word_a: "horse", word_b: "back", score: 8, category: "animals" },
  { word_a: "horse", word_b: "shoe", score: 7, category: "animals" },
  { word_a: "horse", word_b: "power", score: 8, category: "general" },
  { word_a: "power", word_b: "plant", score: 8, category: "general" },
  { word_a: "power", word_b: "house", score: 8, category: "general" },
  { word_a: "power", word_b: "line", score: 8, category: "general" },
  { word_a: "power", word_b: "tool", score: 7, category: "home" },
  { word_a: "plant", word_b: "food", score: 7, category: "nature" },
  { word_a: "plant", word_b: "life", score: 7, category: "nature" },
  { word_a: "play", word_b: "ground", score: 9, category: "sports" },
  { word_a: "play", word_b: "book", score: 8, category: "education" },
  { word_a: "play", word_b: "list", score: 7, category: "music" },
  { word_a: "play", word_b: "pen", score: 6, category: "general" },
  { word_a: "play", word_b: "room", score: 7, category: "home" },
  { word_a: "play", word_b: "date", score: 8, category: "general" },
  { word_a: "run", word_b: "way", score: 8, category: "general" },
  { word_a: "run", word_b: "ner", score: 7, category: "sports" },
  { word_a: "run", word_b: "off", score: 7, category: "general" },
  { word_a: "track", word_b: "and", score: 7, category: "sports" },
  { word_a: "track", word_b: "back", score: 7, category: "music" },
  { word_a: "track", word_b: "ing", score: 7, category: "general" },

  // MUSIC & ARTS
  { word_a: "drum", word_b: "stick", score: 8, category: "music" },
  { word_a: "drum", word_b: "beat", score: 8, category: "music" },
  { word_a: "drum", word_b: "set", score: 7, category: "music" },
  { word_a: "guitar", word_b: "string", score: 8, category: "music" },
  { word_a: "string", word_b: "bean", score: 7, category: "food" },
  { word_a: "string", word_b: "theory", score: 6, category: "music" },
  { word_a: "piano", word_b: "key", score: 7, category: "music" },
  { word_a: "key", word_b: "chain", score: 7, category: "home" },
  { word_a: "key", word_b: "ring", score: 8, category: "home" },
  { word_a: "key", word_b: "word", score: 8, category: "education" },
  { word_a: "key", word_b: "hole", score: 7, category: "home" },
  { word_a: "note", word_b: "book", score: 9, category: "education" },
  { word_a: "note", word_b: "pad", score: 8, category: "education" },
  { word_a: "note", word_b: "card", score: 7, category: "education" },
  { word_a: "song", word_b: "writer", score: 7, category: "music" },
  { word_a: "song", word_b: "bird", score: 7, category: "nature" },
  { word_a: "song", word_b: "book", score: 7, category: "music" },
  { word_a: "music", word_b: "box", score: 8, category: "music" },
  { word_a: "music", word_b: "maker", score: 7, category: "music" },
  { word_a: "music", word_b: "stand", score: 7, category: "music" },
  { word_a: "band", word_b: "stand", score: 7, category: "music" },
  { word_a: "band", word_b: "wagon", score: 7, category: "music" },
  { word_a: "picture", word_b: "frame", score: 8, category: "arts" },
  { word_a: "picture", word_b: "book", score: 7, category: "arts" },
  { word_a: "picture", word_b: "show", score: 7, category: "arts" },
  { word_a: "paint", word_b: "brush", score: 8, category: "arts" },
  { word_a: "paint", word_b: "ball", score: 7, category: "sports" },
  { word_a: "paint", word_b: "box", score: 7, category: "arts" },
  { word_a: "draw", word_b: "back", score: 7, category: "general" },
  { word_a: "draw", word_b: "bridge", score: 7, category: "general" },
  { word_a: "draw", word_b: "ing", score: 7, category: "arts" },

  // TIME & CALENDAR
  { word_a: "day", word_b: "light", score: 9, category: "time" },
  { word_a: "day", word_b: "dream", score: 8, category: "time" },
  { word_a: "day", word_b: "break", score: 9, category: "time" },
  { word_a: "day", word_b: "care", score: 7, category: "time" },
  { word_a: "day", word_b: "time", score: 8, category: "time" },
  { word_a: "day", word_b: "bed", score: 6, category: "time" },
  { word_a: "week", word_b: "end", score: 10, category: "time" },
  { word_a: "week", word_b: "day", score: 8, category: "time" },
  { word_a: "week", word_b: "night", score: 7, category: "time" },
  { word_a: "month", word_b: "ly", score: 6, category: "time" },
  { word_a: "year", word_b: "book", score: 7, category: "time" },
  { word_a: "year", word_b: "ly", score: 6, category: "time" },
  { word_a: "year", word_b: "round", score: 7, category: "time" },
  { word_a: "spring", word_b: "time", score: 9, category: "time" },
  { word_a: "spring", word_b: "break", score: 9, category: "time" },
  { word_a: "spring", word_b: "board", score: 7, category: "nature" },
  { word_a: "summer", word_b: "time", score: 9, category: "time" },
  { word_a: "summer", word_b: "school", score: 8, category: "time" },
  { word_a: "summer", word_b: "break", score: 8, category: "time" },
  { word_a: "winter", word_b: "time", score: 8, category: "time" },
  { word_a: "winter", word_b: "coat", score: 7, category: "time" },
  { word_a: "autumn", word_b: "leaves", score: 7, category: "time" },
  { word_a: "break", word_b: "fast", score: 10, category: "food" },
  { word_a: "break", word_b: "down", score: 8, category: "general" },
  { word_a: "break", word_b: "up", score: 8, category: "general" },
  { word_a: "break", word_b: "out", score: 8, category: "general" },
  { word_a: "break", word_b: "through", score: 7, category: "general" },
  { word_a: "fast", word_b: "food", score: 9, category: "food" },
  { word_a: "fast", word_b: "track", score: 7, category: "general" },
  { word_a: "fast", word_b: "ball", score: 7, category: "sports" },
  { word_a: "time", word_b: "line", score: 8, category: "time" },
  { word_a: "time", word_b: "table", score: 9, category: "time" },
  { word_a: "time", word_b: "frame", score: 8, category: "time" },
  { word_a: "time", word_b: "keeper", score: 7, category: "time" },
  { word_a: "time", word_b: "zone", score: 7, category: "time" },

  // EDUCATION & WORK
  { word_a: "school", word_b: "work", score: 9, category: "education" },
  { word_a: "school", word_b: "yard", score: 8, category: "education" },
  { word_a: "school", word_b: "book", score: 7, category: "education" },
  { word_a: "school", word_b: "bus", score: 8, category: "education" },
  { word_a: "school", word_b: "year", score: 7, category: "education" },
  { word_a: "home", word_b: "work", score: 9, category: "education" },
  { word_a: "home", word_b: "land", score: 7, category: "general" },
  { word_a: "home", word_b: "made", score: 7, category: "home" },
  { word_a: "home", word_b: "less", score: 6, category: "general" },
  { word_a: "book", word_b: "mark", score: 9, category: "education" },
  { word_a: "book", word_b: "store", score: 9, category: "education" },
  { word_a: "book", word_b: "case", score: 8, category: "education" },
  { word_a: "book", word_b: "worm", score: 8, category: "education" },
  { word_a: "book", word_b: "let", score: 6, category: "education" },
  { word_a: "mark", word_b: "down", score: 7, category: "general" },
  { word_a: "mark", word_b: "er", score: 7, category: "education" },
  { word_a: "mark", word_b: "man", score: 6, category: "general" },
  { word_a: "note", word_b: "book", score: 9, category: "education" },
  { word_a: "note", word_b: "booklet", score: 6, category: "education" },
  { word_a: "paper", word_b: "back", score: 8, category: "education" },
  { word_a: "paper", word_b: "work", score: 8, category: "education" },
  { word_a: "paper", word_b: "clip", score: 8, category: "education" },
  { word_a: "paper", word_b: "weight", score: 7, category: "education" },
  { word_a: "paper", word_b: "boy", score: 7, category: "education" },
  { word_a: "paper", word_b: "trail", score: 6, category: "education" },
  { word_a: "news", word_b: "paper", score: 10, category: "education" },
  { word_a: "news", word_b: "letter", score: 8, category: "education" },
  { word_a: "news", word_b: "cast", score: 9, category: "education" },
  { word_a: "news", word_b: "room", score: 7, category: "education" },
  { word_a: "news", word_b: "stand", score: 7, category: "education" },
  { word_a: "work", word_b: "book", score: 7, category: "education" },
  { word_a: "work", word_b: "place", score: 8, category: "education" },
  { word_a: "work", word_b: "shop", score: 8, category: "education" },
  { word_a: "work", word_b: "load", score: 7, category: "education" },
  { word_a: "work", word_b: "out", score: 8, category: "sports" },
  { word_a: "work", word_b: "force", score: 7, category: "general" },
  { word_a: "office", word_b: "work", score: 8, category: "education" },
  { word_a: "office", word_b: "chair", score: 9, category: "education" },
  { word_a: "office", word_b: "building", score: 7, category: "education" },
  { word_a: "office", word_b: "hours", score: 7, category: "education" },
  { word_a: "class", word_b: "room", score: 10, category: "education" },
  { word_a: "class", word_b: "mate", score: 9, category: "education" },
  { word_a: "class", word_b: "work", score: 8, category: "education" },
  { word_a: "class", word_b: "act", score: 6, category: "education" },
  { word_a: "homework", word_b: "help", score: 7, category: "education" },
  { word_a: "test", word_b: "tube", score: 7, category: "education" },
  { word_a: "test", word_b: "drive", score: 7, category: "education" },
  { word_a: "test", word_b: "ing", score: 6, category: "education" },
  { word_a: "lab", word_b: "coat", score: 8, category: "education" },

  // RELATIONSHIPS & PEOPLE
  { word_a: "life", word_b: "guard", score: 9, category: "general" },
  { word_a: "life", word_b: "time", score: 9, category: "general" },
  { word_a: "life", word_b: "style", score: 8, category: "general" },
  { word_a: "life", word_b: "line", score: 7, category: "general" },
  { word_a: "guard", word_b: "dog", score: 8, category: "animals" },
  { word_a: "guard", word_b: "ian", score: 7, category: "general" },
  { word_a: "baby", word_b: "sitter", score: 8, category: "general" },
  { word_a: "baby", word_b: "shower", score: 8, category: "general" },
  { word_a: "baby", word_b: "girl", score: 7, category: "general" },
  { word_a: "baby", word_b: "sit", score: 7, category: "general" },
  { word_a: "baby", word_b: "boom", score: 7, category: "general" },
  { word_a: "mother", word_b: "board", score: 7, category: "general" },
  { word_a: "mother", word_b: "hood", score: 7, category: "general" },
  { word_a: "father", word_b: "land", score: 6, category: "general" },
  { word_a: "grand", word_b: "mother", score: 9, category: "general" },
  { word_a: "grand", word_b: "father", score: 9, category: "general" },
  { word_a: "grand", word_b: "son", score: 7, category: "general" },
  { word_a: "grand", word_b: "child", score: 7, category: "general" },
  { word_a: "step", word_b: "father", score: 8, category: "general" },
  { word_a: "step", word_b: "mother", score: 8, category: "general" },
  { word_a: "step", word_b: "son", score: 7, category: "general" },
  { word_a: "step", word_b: "child", score: 7, category: "general" },
  { word_a: "step", word_b: "ping", score: 6, category: "general" },
  { word_a: "friend", word_b: "ship", score: 9, category: "general" },
  { word_a: "boy", word_b: "friend", score: 9, category: "general" },
  { word_a: "girl", word_b: "friend", score: 9, category: "general" },
  { word_a: "boy", word_b: "hood", score: 7, category: "general" },
  { word_a: "child", word_b: "hood", score: 9, category: "general" },
  { word_a: "child", word_b: "birth", score: 7, category: "general" },
  { word_a: "birth", word_b: "day", score: 10, category: "general" },
  { word_a: "birth", word_b: "place", score: 6, category: "general" },
  { word_a: "love", word_b: "bird", score: 9, category: "general" },
  { word_a: "love", word_b: "ly", score: 7, category: "general" },
  { word_a: "love", word_b: "making", score: 6, category: "general" },

  // TECHNOLOGY
  { word_a: "web", word_b: "site", score: 9, category: "technology" },
  { word_a: "web", word_b: "page", score: 9, category: "technology" },
  { word_a: "web", word_b: "cast", score: 7, category: "technology" },
  { word_a: "web", word_b: "cam", score: 7, category: "technology" },
  { word_a: "web", word_b: "bing", score: 6, category: "technology" },
  { word_a: "web", word_b: "ster", score: 5, category: "technology" },
  { word_a: "home", word_b: "page", score: 9, category: "technology" },
  { word_a: "web", word_b: "inar", score: 6, category: "technology" },
  { word_a: "web", word_b: "log", score: 6, category: "technology" },
  { word_a: "cell", word_b: "phone", score: 10, category: "technology" },
  { word_a: "phone", word_b: "book", score: 8, category: "technology" },
  { word_a: "phone", word_b: "call", score: 9, category: "technology" },
  { word_a: "phone", word_b: "line", score: 8, category: "technology" },
  { word_a: "phone", word_b: "number", score: 9, category: "technology" },
  { word_a: "phone", word_b: "tapping", score: 5, category: "technology" },
  { word_a: "smart", word_b: "phone", score: 10, category: "technology" },
  { word_a: "smart", word_b: "watch", score: 9, category: "technology" },
  { word_a: "smart", word_b: "board", score: 8, category: "technology" },
  { word_a: "watch", word_b: "dog", score: 6, category: "technology" },
  { word_a: "watch", word_b: "man", score: 7, category: "technology" },
  { word_a: "watch", word_b: "tower", score: 7, category: "technology" },
  { word_a: "screen", word_b: "play", score: 7, category: "technology" },
  { word_a: "screen", word_b: "shot", score: 8, category: "technology" },
  { word_a: "screen", word_b: "save", score: 7, category: "technology" },
  { word_a: "laptop", word_b: "case", score: 7, category: "technology" },
  { word_a: "laptop", word_b: "bag", score: 7, category: "technology" },
  { word_a: "computer", word_b: "screen", score: 9, category: "technology" },
  { word_a: "computer", word_b: "keyboard", score: 8, category: "technology" },
  { word_a: "computer", word_b: "mouse", score: 8, category: "technology" },
  { word_a: "mouse", word_b: "trap", score: 8, category: "animals" },
  { word_a: "mouse", word_b: "pad", score: 8, category: "technology" },
  { word_a: "mouse", word_b: "hole", score: 7, category: "animals" },
  { word_a: "data", word_b: "base", score: 9, category: "technology" },
  { word_a: "data", word_b: "set", score: 8, category: "technology" },
  { word_a: "data", word_b: "point", score: 7, category: "technology" },
  { word_a: "data", word_b: "stream", score: 7, category: "technology" },
  { word_a: "cloud", word_b: "computing", score: 8, category: "technology" },
  { word_a: "app", word_b: "store", score: 8, category: "technology" },
  { word_a: "app", word_b: "le", score: 5, category: "technology" },
  { word_a: "user", word_b: "name", score: 8, category: "technology" },
  { word_a: "user", word_b: "guide", score: 7, category: "technology" },
  { word_a: "user", word_b: "role", score: 5, category: "technology" },
  { word_a: "pass", word_b: "word", score: 9, category: "technology" },
  { word_a: "pass", word_b: "code", score: 7, category: "technology" },
  { word_a: "pass", word_b: "key", score: 6, category: "technology" },
  { word_a: "pass", word_b: "over", score: 7, category: "general" },
  { word_a: "pass", word_b: "time", score: 7, category: "general" },

  // GENERAL — useful connectors for chain building
  { word_a: "out", word_b: "side", score: 9, category: "general" },
  { word_a: "out", word_b: "look", score: 8, category: "general" },
  { word_a: "out", word_b: "come", score: 7, category: "general" },
  { word_a: "out", word_b: "rage", score: 7, category: "general" },
  { word_a: "out", word_b: "break", score: 7, category: "general" },
  { word_a: "out", word_b: "burst", score: 6, category: "general" },
  { word_a: "out", word_b: "post", score: 7, category: "general" },
  { word_a: "out", word_b: "door", score: 8, category: "general" },
  { word_a: "out", word_b: "fit", score: 7, category: "general" },
  { word_a: "out", word_b: "let", score: 6, category: "general" },
  { word_a: "out", word_b: "put", score: 7, category: "general" },
  { word_a: "out", word_b: "line", score: 7, category: "general" },
  { word_a: "down", word_b: "town", score: 9, category: "general" },
  { word_a: "down", word_b: "hill", score: 8, category: "general" },
  { word_a: "down", word_b: "pour", score: 7, category: "general" },
  { word_a: "down", word_b: "side", score: 7, category: "general" },
  { word_a: "down", word_b: "fall", score: 8, category: "general" },
  { word_a: "down", word_b: "stair", score: 8, category: "general" },
  { word_a: "down", word_b: "load", score: 9, category: "technology" },
  { word_a: "town", word_b: "hall", score: 9, category: "general" },
  { word_a: "town", word_b: "house", score: 7, category: "general" },
  { word_a: "town", word_b: "ship", score: 6, category: "general" },
  { word_a: "hall", word_b: "way", score: 8, category: "home" },
  { word_a: "hall", word_b: "mark", score: 7, category: "general" },
  { word_a: "hall", word_b: "pass", score: 6, category: "general" },
  { word_a: "over", word_b: "flow", score: 8, category: "general" },
  { word_a: "over", word_b: "load", score: 8, category: "general" },
  { word_a: "over", word_b: "look", score: 8, category: "general" },
  { word_a: "over", word_b: "coat", score: 7, category: "general" },
  { word_a: "over", word_b: "pass", score: 7, category: "general" },
  { word_a: "over", word_b: "time", score: 8, category: "general" },
  { word_a: "over", word_b: "take", score: 6, category: "general" },
  { word_a: "over", word_b: "board", score: 6, category: "general" },
  { word_a: "up", word_b: "side", score: 8, category: "general" },
  { word_a: "up", word_b: "stairs", score: 9, category: "home" },
  { word_a: "up", word_b: "grade", score: 8, category: "general" },
  { word_a: "up", word_b: "date", score: 9, category: "technology" },
  { word_a: "up", word_b: "keep", score: 7, category: "general" },
  { word_a: "up", word_b: "hill", score: 8, category: "general" },
  { word_a: "up", word_b: "set", score: 7, category: "general" },
  { word_a: "up", word_b: "take", score: 8, category: "general" },
  { word_a: "up", word_b: "roar", score: 6, category: "general" },
  { word_a: "up", word_b: "beat", score: 7, category: "general" },
  { word_a: "up", word_b: "front", score: 6, category: "general" },
  { word_a: "up", word_b: "right", score: 6, category: "general" },
  { word_a: "cross", word_b: "walk", score: 9, category: "general" },
  { word_a: "cross", word_b: "word", score: 8, category: "general" },
  { word_a: "cross", word_b: "road", score: 8, category: "general" },
  { word_a: "cross", word_b: "over", score: 7, category: "general" },
  { word_a: "cross", word_b: "fire", score: 7, category: "general" },
  { word_a: "cross", word_b: "ing", score: 6, category: "general" },
  { word_a: "hole", word_b: "punch", score: 8, category: "general" },
  { word_a: "hole", word_b: "digger", score: 6, category: "general" },
  { word_a: "hole", word_b: "some", score: 6, category: "general" },
  { word_a: "punch", word_b: "line", score: 8, category: "general" },
  { word_a: "punch", word_b: "bowl", score: 7, category: "general" },
  { word_a: "dust", word_b: "bowl", score: 7, category: "general" },
  { word_a: "bowl", word_b: "cut", score: 6, category: "general" },
  { word_a: "bowl", word_b: "ing", score: 7, category: "sports" },
  { word_a: "cut", word_b: "off", score: 8, category: "general" },
  { word_a: "cut", word_b: "out", score: 8, category: "general" },
  { word_a: "cut", word_b: "back", score: 7, category: "general" },
  { word_a: "cut", word_b: "ting", score: 6, category: "general" },
  { word_a: "off", word_b: "ramp", score: 7, category: "transport" },
  { word_a: "off", word_b: "spring", score: 7, category: "general" },
  { word_a: "off", word_b: "shoot", score: 7, category: "general" },
  { word_a: "off", word_b: "shore", score: 7, category: "general" },
  { word_a: "off", word_b: "side", score: 6, category: "general" },
  { word_a: "off", word_b: "white", score: 6, category: "general" },
  { word_a: "ramp", word_b: "up", score: 6, category: "general" },

  // ANIMALS
  { word_a: "cat", word_b: "nap", score: 8, category: "animals" },
  { word_a: "cat", word_b: "walk", score: 7, category: "animals" },
  { word_a: "cat", word_b: "bird", score: 6, category: "animals" },
  { word_a: "bird", word_b: "house", score: 8, category: "animals" },
  { word_a: "bird", word_b: "bath", score: 8, category: "animals" },
  { word_a: "bird", word_b: "seed", score: 7, category: "animals" },
  { word_a: "bird", word_b: "cage", score: 7, category: "animals" },
  { word_a: "bird", word_b: "flu", score: 7, category: "animals" },
  { word_a: "cattle", word_b: "call", score: 6, category: "animals" },
  { word_a: "cattle", word_b: "ranch", score: 6, category: "animals" },
  { word_a: "rabbit", word_b: "hole", score: 8, category: "animals" },
  { word_a: "rabbit", word_b: "ears", score: 7, category: "animals" },
  { word_a: "bull", word_b: "dog", score: 7, category: "animals" },
  { word_a: "bull", word_b: "fight", score: 7, category: "animals" },
  { word_a: "bull", word_b: "horn", score: 6, category: "animals" },
  { word_a: "bull", word_b: "market", score: 7, category: "finance" },
  { word_a: "bear", word_b: "market", score: 7, category: "finance" },
  { word_a: "bear", word_b: "hug", score: 8, category: "animals" },
  { word_a: "bear", word_b: "claw", score: 6, category: "animals" },
  { word_a: "wolf", word_b: "pack", score: 8, category: "animals" },
  { word_a: "wolf", word_b: "howl", score: 7, category: "animals" },
  { word_a: "fox", word_b: "hole", score: 6, category: "animals" },
  { word_a: "fox", word_b: "fire", score: 6, category: "animals" },
  { word_a: "horse", word_b: "fly", score: 7, category: "animals" },
  { word_a: "horse", word_b: "play", score: 6, category: "animals" },
  { word_a: "pony", word_b: "tail", score: 7, category: "animals" },
  { word_a: "pony", word_b: "up", score: 6, category: "animals" },
  { word_a: "lamb", word_b: "chops", score: 7, category: "food" },
  { word_a: "chop", word_b: "sticks", score: 6, category: "home" },
  { word_a: "chop", word_b: "ping", score: 6, category: "food" },
  { word_a: "chop", word_b: "house", score: 6, category: "food" },

  // More category bridges
  { word_a: "weight", word_b: "loss", score: 8, category: "health" },
  { word_a: "weight", word_b: "room", score: 7, category: "health" },
  { word_a: "weight", word_b: "lifter", score: 7, category: "sports" },
  { word_a: "loss", word_b: "leader", score: 7, category: "general" },
  { word_a: "loss", word_b: "es", score: 6, category: "general" },
  { word_a: "leader", word_b: "ship", score: 9, category: "general" },
  { word_a: "leader", word_b: "board", score: 8, category: "general" },
  { word_a: "leader", word_b: "line", score: 6, category: "general" },
  { word_a: "wheel", word_b: "chair", score: 9, category: "health" },
  { word_a: "wheel", word_b: "base", score: 7, category: "transport" },
  { word_a: "wheel", word_b: "spin", score: 7, category: "sports" },
  { word_a: "spin", word_b: "class", score: 6, category: "sports" },
  { word_a: "spin", word_b: "off", score: 6, category: "general" },
  { word_a: "bench", word_b: "warm", score: 6, category: "sports" },
  { word_a: "bench", word_b: "mark", score: 7, category: "general" },
  { word_a: "fire", word_b: "place", score: 9, category: "home" },
  { word_a: "fire", word_b: "home", score: 6, category: "home" },
  { word_a: "tie", word_b: "dye", score: 8, category: "arts" },
  { word_a: "tie", word_b: "breaker", score: 7, category: "general" },
  { word_a: "dye", word_b: "cast", score: 7, category: "general" },
  { word_a: "dye", word_b: "job", score: 6, category: "general" },
  { word_a: "job", word_b: "market", score: 8, category: "general" },
  { word_a: "job", word_b: "fair", score: 7, category: "general" },
  { word_a: "job", word_b: "less", score: 6, category: "general" },
  { word_a: "fair", word_b: "ground", score: 7, category: "general" },
  { word_a: "fair", word_b: "well", score: 6, category: "general" },
  { word_a: "well", word_b: "ness", score: 7, category: "health" },
  { word_a: "well", word_b: "spring", score: 7, category: "nature" },
  { word_a: "well", word_b: "done", score: 7, category: "general" },
  { word_a: "done", word_b: "deal", score: 6, category: "general" },

  // More connectors
  { word_a: "flower", word_b: "pot", score: 8, category: "nature" },
  { word_a: "flower", word_b: "bed", score: 7, category: "nature" },
  { word_a: "flower", word_b: "garden", score: 8, category: "nature" },
  { word_a: "pot", word_b: "luck", score: 7, category: "food" },
  { word_a: "pot", word_b: "belly", score: 6, category: "food" },
  { word_a: "pot", word_b: "shot", score: 6, category: "general" },
  { word_a: "luck", word_b: "charm", score: 7, category: "general" },
  { word_a: "luck", word_b: "iest", score: 6, category: "general" },
  { word_a: "luck", word_b: "less", score: 5, category: "general" },
  { word_a: "charm", word_b: "bracelet", score: 7, category: "general" },
  { word_a: "charm", word_b: "school", score: 6, category: "general" },
  { word_a: "charm", word_b: "ing", score: 6, category: "general" },
  { word_a: "print", word_b: "shop", score: 7, category: "home" },
  { word_a: "print", word_b: "out", score: 8, category: "technology" },
  { word_a: "shop", word_b: "lift", score: 7, category: "transport" },
  { word_a: "shop", word_b: "keep", score: 6, category: "general" },
  { word_a: "shop", word_b: "per", score: 7, category: "general" },
  { word_a: "lift", word_b: "gate", score: 6, category: "transport" },
  { word_a: "lift", word_b: "off", score: 7, category: "transport" },
  { word_a: "gate", word_b: "way", score: 7, category: "home" },
  { word_a: "gate", word_b: "keeper", score: 7, category: "general" },
  { word_a: "trail", word_b: "mix", score: 6, category: "food" },
  { word_a: "trail", word_b: "blazer", score: 6, category: "nature" },
  { word_a: "trail", word_b: "head", score: 6, category: "nature" },
  { word_a: "mix", word_b: "tape", score: 7, category: "music" },
  { word_a: "mix", word_b: "up", score: 7, category: "general" },
  { word_a: "hook", word_b: "up", score: 7, category: "general" },
  { word_a: "hook", word_b: "line", score: 7, category: "general" },
  { word_a: "hook", word_b: "shot", score: 6, category: "sports" },
  { word_a: "pipe", word_b: "line", score: 7, category: "general" },
  { word_a: "pipe", word_b: "dream", score: 6, category: "general" },
  { word_a: "pipe", word_b: "fitter", score: 6, category: "general" },

  // CLOTHING & FASHION
  { word_a: "hat", word_b: "box", score: 6, category: "fashion" },
  { word_a: "hat", word_b: "band", score: 6, category: "fashion" },
  { word_a: "coat", word_b: "hanger", score: 7, category: "home" },
  { word_a: "coat", word_b: "rack", score: 7, category: "home" },
  { word_a: "coat", word_b: "room", score: 7, category: "home" },
  { word_a: "shoe", word_b: "lace", score: 8, category: "fashion" },
  { word_a: "shoe", word_b: "box", score: 7, category: "fashion" },
  { word_a: "shoe", word_b: "maker", score: 6, category: "fashion" },
  { word_a: "lace", word_b: "work", score: 6, category: "fashion" },
  { word_a: "lace", word_b: "up", score: 6, category: "fashion" },
  { word_a: "belt", word_b: "loop", score: 6, category: "fashion" },
  { word_a: "belt", word_b: "way", score: 6, category: "transport" },
  { word_a: "pocket", word_b: "book", score: 7, category: "fashion" },
  { word_a: "pocket", word_b: "knife", score: 7, category: "fashion" },
  { word_a: "pocket", word_b: "watch", score: 7, category: "fashion" },
  { word_a: "pocket", word_b: "money", score: 6, category: "finance" },
  { word_a: "shirt", word_b: "tail", score: 6, category: "fashion" },
  { word_a: "shirt", word_b: "front", score: 6, category: "fashion" },
  { word_a: "jeans", word_b: "pocket", score: 7, category: "fashion" },
  { word_a: "dress", word_b: "code", score: 8, category: "fashion" },
  { word_a: "dress", word_b: "shirt", score: 8, category: "fashion" },
  { word_a: "dress", word_b: "maker", score: 6, category: "fashion" },
  { word_a: "dress", word_b: "er", score: 7, category: "home" },
  { word_a: "suit", word_b: "case", score: 9, category: "fashion" },
  { word_a: "suit", word_b: "up", score: 6, category: "fashion" },
  { word_a: "rain", word_b: "coat", score: 8, category: "fashion" },
  { word_a: "rain", word_b: "wear", score: 6, category: "fashion" },
  { word_a: "night", word_b: "gown", score: 7, category: "fashion" },
  { word_a: "pajama", word_b: "party", score: 6, category: "fashion" },
  { word_a: "sweat", word_b: "shirt", score: 7, category: "fashion" },
  { word_a: "sweat", word_b: "er", score: 7, category: "fashion" },
  { word_a: "swim", word_b: "suit", score: 9, category: "fashion" },
  { word_a: "swim", word_b: "mer", score: 6, category: "sports" },
  { word_a: "swim", word_b: "ming", score: 7, category: "sports" },

  // Additional easy bridges
  { word_a: "box", word_b: "spring", score: 7, category: "home" },
  { word_a: "box", word_b: "office", score: 9, category: "general" },
  { word_a: "box", word_b: "room", score: 7, category: "home" },
  { word_a: "box", word_b: "top", score: 6, category: "general" },
  { word_a: "box", word_b: "er", score: 7, category: "sports" },
  { word_a: "spring", word_b: "roll", score: 7, category: "food" },
  { word_a: "spring", word_b: "clean", score: 7, category: "home" },
  { word_a: "roll", word_b: "call", score: 8, category: "general" },
  { word_a: "roll", word_b: "cake", score: 7, category: "food" },
  { word_a: "roll", word_b: "back", score: 6, category: "general" },
  { word_a: "call", word_b: "back", score: 7, category: "general" },
  { word_a: "call", word_b: "out", score: 8, category: "general" },
  { word_a: "call", word_b: "box", score: 6, category: "general" },
  { word_a: "call", word_b: "ing", score: 7, category: "general" },
  { word_a: "clean", word_b: "up", score: 8, category: "home" },
  { word_a: "clean", word_b: "out", score: 6, category: "home" },
  { word_a: "clean", word_b: "room", score: 6, category: "home" },
  { word_a: "clean", word_b: "ing", score: 7, category: "home" },

  // More simple connector words for chain building
  { word_a: "post", word_b: "office", score: 9, category: "general" },
  { word_a: "post", word_b: "card", score: 8, category: "general" },
  { word_a: "post", word_b: "man", score: 8, category: "general" },
  { word_a: "post", word_b: "box", score: 7, category: "general" },
  { word_a: "post", word_b: "mark", score: 6, category: "general" },
  { word_a: "post", word_b: "age", score: 6, category: "general" },
  { word_a: "card", word_b: "board", score: 8, category: "general" },
  { word_a: "card", word_b: "game", score: 8, category: "general" },
  { word_a: "card", word_b: "holder", score: 6, category: "general" },
  { word_a: "card", word_b: "inal", score: 6, category: "general" },
  { word_a: "card", word_b: "igan", score: 6, category: "fashion" },
  { word_a: "card", word_b: "stock", score: 6, category: "general" },
  { word_a: "stock", word_b: "room", score: 6, category: "general" },
  { word_a: "stock", word_b: "pile", score: 6, category: "general" },
  { word_a: "stock", word_b: "ing", score: 7, category: "fashion" },
  { word_a: "stock", word_b: "market", score: 9, category: "finance" },
  { word_a: "market", word_b: "place", score: 8, category: "finance" },
  { word_a: "market", word_b: "ing", score: 8, category: "finance" },
  { word_a: "crowd", word_b: "surf", score: 6, category: "music" },
  { word_a: "crowd", word_b: "ed", score: 5, category: "general" },
  { word_a: "surf", word_b: "board", score: 9, category: "sports" },
  { word_a: "surf", word_b: "ing", score: 8, category: "sports" },
  { word_a: "surf", word_b: "cast", score: 6, category: "technology" },
  { word_a: "surf", word_b: "side", score: 6, category: "nature" },
  { word_a: "board", word_b: "ing", score: 6, category: "general" },
  { word_a: "room", word_b: "board", score: 5, category: "general" },
  { word_a: "room", word_b: "ful", score: 5, category: "general" },

  // Story/book related
  { word_a: "story", word_b: "board", score: 8, category: "education" },
  { word_a: "story", word_b: "book", score: 7, category: "education" },
  { word_a: "story", word_b: "teller", score: 7, category: "education" },
  { word_a: "cover", word_b: "age", score: 6, category: "general" },
  { word_a: "cover", word_b: "let", score: 5, category: "general" },
  { word_a: "cover", word_b: "up", score: 7, category: "general" },
  { word_a: "cover", word_b: "ing", score: 6, category: "general" },
  { word_a: "cover", word_b: "all", score: 5, category: "general" },

  // House parts
  { word_a: "house", word_b: "hold", score: 9, category: "home" },
  { word_a: "house", word_b: "work", score: 8, category: "home" },
  { word_a: "house", word_b: "plant", score: 8, category: "home" },
  { word_a: "house", word_b: "top", score: 7, category: "home" },
  { word_a: "house", word_b: "boat", score: 7, category: "home" },
  { word_a: "house", word_b: "coat", score: 6, category: "home" },
  { word_a: "house", word_b: "keeping", score: 6, category: "home" },
  { word_a: "hold", word_b: "up", score: 8, category: "general" },
  { word_a: "hold", word_b: "ing", score: 6, category: "general" },
  { word_a: "hold", word_b: "down", score: 7, category: "general" },
  { word_a: "hold", word_b: "out", score: 6, category: "general" },
  { word_a: "hold", word_b: "er", score: 6, category: "general" },

  // Store/shopping
  { word_a: "store", word_b: "front", score: 7, category: "general" },
  { word_a: "store", word_b: "room", score: 7, category: "home" },
  { word_a: "store", word_b: "keeper", score: 6, category: "general" },
  { word_a: "store", word_b: "age", score: 6, category: "general" },
  { word_a: "grocery", word_b: "store", score: 9, category: "food" },
  { word_a: "hardware", word_b: "store", score: 8, category: "home" },
  { word_a: "drug", word_b: "store", score: 8, category: "health" },
  { word_a: "book", word_b: "store", score: 9, category: "education" },
  { word_a: "pet", word_b: "store", score: 7, category: "animals" },
  { word_a: "shop", word_b: "lift", score: 7, category: "transport" },
  { word_a: "shop", word_b: "ping", score: 7, category: "general" },
  { word_a: "shop", word_b: "per", score: 6, category: "general" },

  // Weather more
  { word_a: "weather", word_b: "man", score: 7, category: "nature" },
  { word_a: "weather", word_b: "proof", score: 6, category: "nature" },
  { word_a: "weather", word_b: "beaten", score: 5, category: "nature" },
  { word_a: "rain", word_b: "check", score: 6, category: "general" },
  { word_a: "rain", word_b: "maker", score: 5, category: "nature" },
  { word_a: "snow", word_b: "plow", score: 7, category: "transport" },
  { word_a: "wind", word_b: "mill", score: 8, category: "nature" },
  { word_a: "wind", word_b: "shield", score: 7, category: "transport" },
  { word_a: "wind", word_b: "breaker", score: 6, category: "fashion" },
  { word_a: "wind", word_b: "pipe", score: 5, category: "music" },
];

/* ------------------------------------------------------------------ */
/*  Main seed logic                                                    */
/* ------------------------------------------------------------------ */

function mangleWord(word: string): string {
  return word.toLowerCase().replace(/[^a-z0-9\-']/g, "");
}

async function seed() {
  console.log(`Seeding ${PHRASES.length} phrase pairs into chain_phrases...\n`);

  let inserted = 0;
  let skipped = 0;
  let errors = 0;

  for (const entry of PHRASES) {
    const wordA = mangleWord(entry.word_a);
    const wordB = mangleWord(entry.word_b);
    const phraseText = `${wordA} ${wordB}`;

    const { error } = await db.from("chain_phrases").insert({
      word_a: wordA,
      word_b: wordB,
      phrase: phraseText,
      commonness_score: entry.score,
      category: entry.category,
      source: "seed-phrases",
      is_active: true,
    });

    if (error) {
      if (error.code === "23505") {
        skipped++;
        continue;
      }
      console.error(`  Error inserting "${phraseText}": ${error.message}`);
      errors++;
    } else {
      inserted++;
    }
  }

  console.log(`\nDone! Inserted: ${inserted}, Skipped: ${skipped}, Errors: ${errors}`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
