import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/lib/supabase/database.types";
import { generateChains } from "./generator";
import { validateChainWithLlm } from "./llm-validate";
import { scheduleNextApprovedPuzzle } from "./schedule-service";

export interface TopUpOptions {
  /** UTC date to start from; defaults to today. */
  today?: string;
  /** How many days beyond `today` to keep filled. */
  daysAhead?: number;
}

export interface TopUpEntry {
  date: string;
  /** `none` means nothing passed the checks; the on-visit path covers that day. */
  source: "approved" | "generated" | "none";
  words?: string[];
}

/** Generated chains tried per date before giving up on it. */
const CANDIDATES_PER_DATE = 8;

function addDays(date: string, days: number): string {
  const d = new Date(`${date}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

/**
 * Keeps the daily calendar filled from `today` through `daysAhead` days out.
 * Each empty date takes the next approved puzzle, or failing that a
 * generated chain that passes the LLM phrase check.
 */
export async function topUpDailyChains(
  db: SupabaseClient<Database>,
  options: TopUpOptions = {},
): Promise<TopUpEntry[]> {
  const today = options.today ?? new Date().toISOString().slice(0, 10);
  const daysAhead = options.daysAhead ?? 7;

  const { data: scheduled, error } = await db
    .from("daily_chain_puzzles")
    .select("publish_date")
    .gte("publish_date", today);
  if (error) throw new Error(`Failed to load schedule: ${error.message}`);

  const taken = new Set((scheduled ?? []).map((row) => row.publish_date));
  const report: TopUpEntry[] = [];

  // One date at a time: each pick must see the links the previous one used.
  for (let offset = 0; offset <= daysAhead; offset++) {
    const date = addDays(today, offset);
    if (taken.has(date)) continue;

    if (await scheduleNextApprovedPuzzle(db, date)) {
      report.push({ date, source: "approved" });
      continue;
    }

    const words = await scheduleGeneratedChain(db, date);
    report.push(words ? { date, source: "generated", words } : { date, source: "none" });
  }

  return report;
}

async function scheduleGeneratedChain(
  db: SupabaseClient<Database>,
  date: string,
): Promise<string[] | null> {
  const candidates = await generateChains(db, {
    length: 5,
    count: CANDIDATES_PER_DATE,
    minLinkScore: 5,
  });

  for (const chain of candidates) {
    const validation = await validateChainWithLlm(chain.words);
    if (!validation.allValid) continue;

    const { data: inserted, error: insertError } = await db
      .from("chain_puzzles")
      .insert({
        title: chain.words.join(" → "),
        words: chain.words,
        phrases: chain.phrases,
        difficulty: chain.difficulty,
        theme: chain.theme,
        status: "scheduled",
        score: chain.score,
        notes: "Generated by the daily top-up and LLM-checked; not human-reviewed.",
        created_by: "cron",
      })
      .select("id")
      .single();
    if (insertError || !inserted) {
      throw new Error(`Failed to save generated chain: ${insertError?.message}`);
    }

    const { error: scheduleError } = await db
      .from("daily_chain_puzzles")
      .insert({ publish_date: date, puzzle_id: inserted.id });
    // Another request claimed the date while we worked; theirs stands.
    if (scheduleError?.code === "23505") return null;
    if (scheduleError) {
      throw new Error(`Failed to schedule generated chain: ${scheduleError.message}`);
    }

    return chain.words;
  }

  return null;
}
